name: FastAPI Backend CI/CD
on:
  push:
    branches: [ "main" ] 

permissions:
  contents: write
  
jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4
        with:
         fetch-depth: 0 
           
      - name: 2. Run Robot Framework Tests
        run: |
          docker compose up --build --exit-code-from robot_tester
          
      - name: 3. Promote to Release Branch
        if: success() 
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git push origin HEAD:release --force
